# Cloud Build config: build & deploy React frontend from the frontend directory
steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'frontend'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/homebuyeragent:$SHORT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/homebuyeragent:$SHORT_SHA'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      BACKEND_URL=$(gcloud run services describe homebuyerassistant --region=us-central1 --format="value(status.url)")
      gcloud run deploy homebuyeragent \
        --image gcr.io/$PROJECT_ID/homebuyeragent:$SHORT_SHA \
        --platform managed \
        --region us-central1 \
        --allow-unauthenticated \
        --set-env-vars REACT_APP_API_URL=$BACKEND_URL

# Specify substitutions or timeouts as needed
substitutions:
  _REGION: "us-central1"
  _SERVICE: "homebuyeragent"
timeout: "1200s"
